### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [oscarmaxgithub/MarketSpring#1]
Hi,<br><br>url : https://github.com/oscarmaxgithub/MarketSpring/blob/a3dea2d6936c3bfb52a34c1622c3f6314774c1a4/src/main/resources/application-pdn.properties <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by oscarmaxgithub** [comment]
thanks, i do it now 👍
